### ISSUE TITLE
fix date formats

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/libsys-webforms#102]
While testing out a mailer, I deployed to dev, and tried to create a UniUpdatesBatch, which threw an error:

`Completed 500 Internal Server Error in 598ms (ActiveRecord: 515.9ms)
OCIError (ORA-02289: sequence does not exist):
  app/models/uni_updates_batch.rb:11:in `create_item_type_batch'
  app/controllers/change_item_types_controller.rb:13:in `create'`

Here's `app/models/uni_updates_batch.rb:11`:

`create(batch_date: params[:change_item_type][:batch_date],`

The rails app understands the `:batch_date` to be `2016-06-07 16:57:34 -0700`, which is a different format compared to the database values, for example, `13-NOV-98`.

My guess is that the formatting mismatch is the source of the error, and anyway, we should have the rails app creating date stamps according to how the database expects them.

**Comment by tallenaz** [comment]
Fixed by #105 although there's still an issue with being able to create an object. I'll make a separate issue for that.
