### ISSUE TITLE
Fix OCIError: ORA-02289: sequence does not exist

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/libsys-webforms#108]
```
2.2.0 :001 > uub=UniUpdatesBatch.new
   (18.7ms)  SELECT column_name AS name, data_type AS sql_type, data_default, nullable, virtual_column, hidden_column, data_type_owner AS sql_type_owner, DECODE(data_type, 'NUMBER', data_precision, 'FLOAT', data_precision, 'VARCHAR2', DECODE(char_used, 'C', char_length, data_length), 'RAW', DECODE(char_used, 'C', char_length, data_length), 'CHAR', DECODE(char_used, 'C', char_length, data_length), NULL) AS limit, DECODE(data_type, 'NUMBER', data_scale, NULL) AS scale FROM all_tab_cols WHERE owner = 'ORA_SUL' AND table_name = 'UNI_UPDATES_BATCH' AND hidden_column = 'NO' ORDER BY column_id
 => #<UniUpdatesBatch batch_id: nil, batch_date: nil, user_name: nil, user_email: nil, action: nil, priority: nil, export_yn: nil, check_bc_first: nil, orig_lib: nil, new_lib: nil, new_homeloc: nil, new_curloc: nil, new_itype: nil, total_bcs: nil, pending: nil, comments: nil, num_errors: nil> 
2.2.0 :002 > uub.save
   (115.1ms)  SELECT DECODE(table_name, UPPER(table_name), LOWER(table_name), table_name) FROM all_tables WHERE owner = SYS_CONTEXT('userenv', 'current_schema') AND secondary = 'N'
  Sequence (1.2ms)  select us.sequence_name from all_sequences us where us.sequence_owner = 'ORA_SUL' and us.sequence_name = 'UNI_UPDATES_BATCH_SEQ'
  Primary Key (8.1ms)  SELECT cc.column_name FROM all_constraints c, all_cons_columns cc WHERE c.owner = 'ORA_SUL' AND c.table_name = 'UNI_UPDATES_BATCH' AND c.constraint_type = 'P' AND cc.owner = c.owner AND cc.constraint_name = c.constraint_name
  Primary Key Trigger (2.6ms)            SELECT trigger_name
          FROM all_triggers
          WHERE owner = 'ORA_SUL'
            AND trigger_name = 'UNI_UPDATES_BATCH_PKT'
            AND table_owner = 'ORA_SUL'
            AND table_name = 'UNI_UPDATES_BATCH'
            AND status = 'ENABLED'

OCIError: ORA-02289: sequence does not exist
    from stmt.c:243:in oci8lib_220.so
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/ruby-oci8-2.2.1/lib/oci8/cursor.rb:126:in `exec'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/ruby-oci8-2.2.1/lib/oci8/oci8.rb:280:in `exec_internal'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/ruby-oci8-2.2.1/lib/oci8/oci8.rb:271:in `exec'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:435:in `exec'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:184:in `select'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced/connection.rb:83:in `select_one'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced/connection.rb:89:in `select_value'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:762:in `next_sequence_value'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/relation.rb:48:in `insert'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/persistence.rb:524:in `_create_record'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/counter_cache.rb:139:in `_create_record'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/locking/optimistic.rb:75:in `_create_record'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/attribute_methods/dirty.rb:132:in `_create_record'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/callbacks.rb:306:in `block in _create_record'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
... 23 levels...
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/transactions.rb:220:in `transaction'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/transactions.rb:286:in `block in save'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/transactions.rb:285:in `save'
    from (irb):2
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/console.rb:110:in `start'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/console.rb:9:in `start'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /opt/app/libsys/libsys-webforms/shared/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/commands.rb:17:in `<top (required)>'
    from ./bin/rails:4:in `require'
    from ./bin/rails:4:in `<main>'
```

Trying to change an item type through the ui also reports the same `ORA-02289: sequence does not exist` error at 

```
def self.create_item_type_batch(params)
    create(batch_date: params[:change_item_type][:batch_date],
           user_name: params[:change_item_type][:user_name],
           user_email: params[:change_item_type][:email],
           orig_lib: params[:change_item_type][:current_library],
```

**Comment by tallenaz** [comment]
possible workaround: http://niranjansarade.blogspot.com/2011/03/avoid-oracle-sequence-during.html

**Comment by tallenaz** [comment]
Julian created the needed sequence for us.
