### ISSUE TITLE
Error submitting ILLiad user export form

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-webforms#628]
```
Processing by IlliadUserExportsController#create as HTML
  Parameters: {"utf8"=>"✓", 
"authenticity_token"=>"REDACTED", 
"illiad_user_export"=>{"sunet_ids"=>"sdoljack\r\n"}, 
"commit"=>"Submit IDs for Export"}
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)

TypeError (no implicit conversion of nil into String):
  
app/models/illiad_user_export.rb:8:in `initialize'
app/models/illiad_user_export.rb:8:in `open'
app/models/illiad_user_export.rb:8:in `write_ids'
app/controllers/illiad_user_exports_controller.rb:12:in `create'
```

**Comment by shelleydoljack** [comment]
Same issue happens when trying to do a user load rerun.
